### ISSUE TITLE
Proxied SVG-Files: C-style comment syntax" in category "unix" has been triggered by request header 

### ISSUE THREAD

**Issue by anarchist912** [RuiSiang/PoW-Shield#222]
.svg-Files won't get loaded through the PoW-Shield, it logs:

![image](https://user-images.githubusercontent.com/30655359/147524539-ad1501e0-1caa-41a6-8da2-81f3cc46e7e4.png)

Is there anything I can do about this?

Thank you very much for this great software!!

**Comment by RuiSiang** [comment]
Hi, you can use `WAF_HEADER_EXCLUDE_RULES` environmental variable to ignore WAF rules (see CONFIGURE.md for more information).
