### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by libDarkstreet** [RuiSiang/PoW-Shield#436]
Hi, for some reason it returns a 401 error on submit stage.
I've tried with and without reverse proxy, in both cases I get a 401 error. 
I don't see anything in the logs.

**Comment by libDarkstreet** [comment]
After a few tries I found out that it works locally but not on my server. I tried the exact same compose file that worked locally and for some reason it still won't work.

**Comment by RuiSiang** [comment]
I cannot triage or do anything without more information.

**Comment by RuiSiang** [comment]
Closed for inactivity
