### ISSUE TITLE
Hey this is a sugestion

### ISSUE THREAD

**Issue by keiranchippendaleuk** [RuiSiang/PoW-Shield#439]
what you should do is make this support multi domains going to diff ips and ports and build in the dashboard and make it so you can add and remove domains and alot of other things on their and allow you to add multi edge servers to spread the load

**Comment by RuiSiang** [comment]
This should be an issue for Phalanx. Hypothetically, PoW-Phalanx should be able to control the number of active instances of PoW-Shield, hence controlling the number of instances for each domain.

The main reason for keeping each PoW-Shield Instance to one domain is to ensure the atomicity of the container. Different domains should have different patterns when under attack, and face different attack vectors.

I don't have time right now, but will get on it in the future.

**Comment by keiranchippendaleuk** [comment]
so would i be able to rub everything and add more then one domain pointing it in different places

**Comment by RuiSiang** [comment]
That issue is irrelevant in this specific repository. Yes, but with assistance of PoW-Phalanx in the future.

**Comment by thefirst100yearsaredifficult** [comment]
Hey guys, so @RuiSiang as I understand it is not something that is currently avaialble? More of a future things, right? Also amazing project man, keep up the good work!

**Comment by RuiSiang** [comment]
Thanks. Yes, I'll work on it when I have time, but it'll be implemented in [PoW Phalanx](https://github.com/RuiSiang/PoW-Phalanx ). It'll make the structure easier to maintain.
