### ISSUE TITLE
Not Protected

### ISSUE THREAD

**Issue by cyberceros** [RuiSiang/PoW-Shield#459]
![image](https://github.com/RuiSiang/PoW-Shield/assets/42605479/2b3a959d-ae89-443a-9df9-7386c79e6726)
![image](https://github.com/RuiSiang/PoW-Shield/assets/42605479/a4d829f3-edf5-4251-8c58-3f0113ff69e0)
Permanent Link of Check-host report: https://check-host.net/check-report/1090bbb9k693
---------------------------------------------------------------------------------------
The protection needs to be improved, how I tested

![image](https://github.com/RuiSiang/PoW-Shield/assets/42605479/92ec1af4-a2fd-454e-8b46-48d19cce6e36)
Passed the JS challenge on a real browser, 
![image](https://github.com/RuiSiang/PoW-Shield/assets/42605479/599b313b-c525-43dc-b0e7-169a83d6bed2)
Try to pass the same request via Postman, the request was bypassed, hence no additional auth was requested by the server (no js challenge)...

then created a request in nodejs and uploaded it on my 16 core machines and reloading proxies and hitting enter...then the traffic bypassed CF as well as this protection :)
one more check-host report link after 5 min: https://check-host.net/check-report/1090be48k95

Not able to filter out.... improve....

**Comment by RuiSiang** [comment]
That's just a demo page with a celeron processor, won't be putting up infrastructure for an OSS demo. What do you expect?
