### ISSUE TITLE
Question: How does this protect the "PoW Shield" from DDoS?

### ISSUE THREAD

**Issue by sebastianstucke87** [RuiSiang/PoW-Shield#479]
According to this slide, you can simply flood the `PoW Shield` to prevent all clients to be validated and proxied to the `Protected Server`. Is this correct?

> ![VS--YouTube-TheToolBoxPoWShield-10’14”](https://github.com/RuiSiang/PoW-Shield/assets/47354551/98091746-ffe8-4e41-8002-b5521c89b8fc)

**Comment by RuiSiang** [comment]
Yes, in production you'll need to autoscale the PoW Shield container. However, request computational cost is extremely low on PoW Shield, which leads to you only having to pay for a fractional of the cost when compared with the requests going directly to the protected server. It also has internal rate limiting and firewall functionality to block malicious intent up to a certain degree. Hope that clarifies.
